import { useEffect, type ReactNode } from "react";
import { Sidebar } from "./Sidebar";
import { Topbar } from "./Topbar";
import { MobileNav } from "./MobileNav";
import { useStore } from "@/lib/store";
import { useSettings } from "@/lib/settings";

export function AppShell({ children }: { children: ReactNode }) {
  const hydrate = useStore((s) => s.hydrateFromDb);
  const conn = useSettings((s) => s.neonConnectionString);
  useEffect(() => {
    if (conn) void hydrate();
  }, [conn, hydrate]);

  return (
    <div className="flex min-h-screen bg-grid">
      <div className="hidden md:flex">
        <Sidebar />
      </div>
      <div className="flex min-w-0 flex-1 flex-col">
        <Topbar />
        <main className="flex-1 px-4 py-6 pb-24 sm:px-6 sm:py-8 md:pb-8">{children}</main>
      </div>
      <MobileNav />
      <PrintFooter />
    </div>
  );
}

function PrintFooter() {
  return (
    <div className="print-footer">
      Generated by BizLens AI · {new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}
    </div>
  );
}
